spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5435/nbts?currentSchema=leagues
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application:
    name: nbts
    version: @project.version@
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration/leagues
    #create-schemas: true
  docker:
    compose:
      file: ./docker-compose.yml

nbts:
  rapidApi:
    key: ${RAPID_API_KEY}

server:
  servlet:
    context-path: /nbts
  port: 8080

logging:
  level:
    root: INFO
    be.boets: DEBUG
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
