CREATE TABLE IF NOT EXISTS leagues.country(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name_nl VARCHAR NOT NULL,
                        name_en VARCHAR NOT NULL,
                        country_code VARCHAR NOT NULL,
                        region VARCHAR NOT NULL,
                        flag_url VARCHAR NOT NULL
);

CREATE INDEX country_name_idx ON leagues.country(name_en, country_code);
