CREATE TABLE country(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nameNL VARCHAR NOT NULL,
                        nameEN VARCHAR NOT NULL,
                        country_code VARCHAR NOT NULL,
                        flag_url VARCHAR NOT NULL
);

CREATE INDEX country_name_idx ON country(nameNL, country_code);
