CREATE TABLE IF NOT EXISTS leagues.league(
                                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              name VARCHAR NOT NULL,
                                              league_id INTEGER NOT NULL,
                                              country_code VARCHAR NOT NULL,
                                              start_season DATE NOT NULL,
                                              end_season DATE NOT NULL,
                                              season INTEGER NOT NULL,
                                              logo VARCHAR NOT NULL,
                                              current BOOLEAN NOT NULL,
                                              unique (league_id, country_code)
);

CREATE INDEX leagues_name_idx ON leagues.league(name, league_id, country_code);
