CREATE TABLE IF NOT EXISTS admin.api_counter (
                                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             date DATE NOT NULL,
                                             counter INTEGER NOT NULL,
                                             unique (date)
);

CREATE INDEX api_counter_date_idx ON admin.api_counter(date);
